# Generated by Django 5.2.1 on 2025-06-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_last_seen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameLog',
        ),
    ]
